import type { Metadata } from "next";
import { Dosis, Inter} from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

const dosis = Dosis({ subsets: ["latin"], weight: ['400', '700'], variable:'--font-dosis'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dosis.className}>{children}</body>
    </html>
  );
}
